server:
  port: 8787

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ums
    username: postgres
    password: Postgres@298
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: login
    hibernate:
      ddl-auto: update